### ISSUE TITLE
BenchmarkDotNet claims the assembly is not optimized (Built in DEBUG)

### ISSUE THREAD

**Issue by SpiritBob** [ChrisHodges/LightweightExcelReader#9]
Could you please build the nuGet package in RELEASE mode?

**Comment by ChrisHodges** [comment]
Hi SpiritBob. LightweightExcelReader is still officially in beta so distributing debug builds is a deliberate choice (we get better stack traces when someone reports an issue). The official release version (i.e. v.1.0.0) will be out shortly and that will be built in release mode. 

In the meantime, you're able to build the package yourself and run the benchmarks locally.

**Comment by SpiritBob** [comment]
Got it, thank you Chris. Consider perhaps mentioning this in the docs somewhere, although soon when the official versions start rolling out, you won't need to.

**Comment by silkfire** [comment]
Are we still in beta?
